version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=deployments.settings
    volumes:
      - static_volume:/app/staticfiles

volumes:
  static_volume:
